some cleanup

diff --git a/sbin/zram-init b/sbin/zram-init
--- a/sbin/zram-init
+++ b/sbin/zram-init
@@ -27,7 +27,7 @@ Fatal() {
 }
 
 Push() {
-	PushA_=`push.sh 2>/dev/null` || Fatal \
+	PushA_=$(push.sh 2>/dev/null) || Fatal \
 'push.sh from https://github.com/vaeth/push (v2.0 or newer) required'
 	eval "$PushA_"
 	Push "$@"
@@ -35,7 +35,7 @@ Push() {
 
 IsNumeric() {
 	case ${1:-x} in
-	*[!01234567890]*)
+	*[!0-9]*)
 		return 1;;
 	esac
 	:
@@ -87,7 +87,7 @@ If you have push.sh in \$PATH, you can also use accumulatively:
 -M ARG   Pass ARG to the respective swapon/mount call
 -2 ARG   Pass ARG to the tune2fs call (ignored unless for ext2 or ext4)
 -Z ARG   Pass ARG to the zramctl call"
-	exit ${1:-1}
+	exit "${1:-1}"
 }
 
 PATH=${PATH-}${PATH:+:}/usr/sbin:/sbin
@@ -142,7 +142,7 @@ do	case $opt in
 	*)	Usage 0;;
 	esac
 done
-shift $(( $OPTIND -1 ))
+shift $(( OPTIND -1 ))
 [ $# -eq 1 ] || [ $# -eq 2 ] || Usage
 
 if $zramctl
@@ -150,13 +150,13 @@ then	command -v zramctl >/dev/null 2>&1 || zramctl=false
 fi
 
 # Defaults for empty/unspecified options:
-: ${dev:=0} ${prio:=16383} ${fstype:=ext4}
+: "${dev:=0}" "${prio:=16383}" "${fstype:=ext4}"
 
 IsNumeric "$dev" || Fatal "device $dev is not numeric"
 IsNumeric "${1:-0}" || Fatal "size $1 is not numeric"
 
 umount=:
-if [ ${1:-0} -ne 0 ]
+if [ "${1:-0}" -ne 0 ]
 then	umount=false
 	size=$(( $1 * 1024 * 1024 )) && [ $size -gt 0 ] || \
 		Fatal 'failed to calculate size'
@@ -185,7 +185,7 @@ HotAdd() {
 	do	curradd=
 		exec 3<&0 && {
 			exec <"$zclass/hot_add" && \
-				read curradd || curradd=
+				read -r curradd || curradd=
 			exec 0<&3
 			exec 3<&-
 		}
@@ -198,7 +198,7 @@ HotAdd() {
 	sleep=0
 	while ! test -b "$devnode"
 	do	sleep 1
-		sleep=$(( $sleep + 1 ))
+		sleep=$(( sleep + 1 ))
 		[ $sleep -lt 5 ] || Fatal "failed to create $devnode"
 	done
 }
@@ -210,7 +210,7 @@ then	$umount && exit
 	sleep=0
 	while ! test -b "$devnode" && ! test -d "$zclass"
 	do	sleep 1
-		sleep=$(( $sleep + 1 ))
+		sleep=$(( sleep + 1 ))
 		[ $sleep -lt 5 ] || \
 			Fatal "cannot create $devnode: $zclass missing"
 	done
@@ -236,7 +236,7 @@ then	if $swap
 		then	zramctl --reset -- "$devnode" || status=$?
 		else	SysCtl 1 "$block/reset" || status=$?
 			if $umount && test -w "$zclass/hot_remove"
-			then	SysCtl "$device" "$zclass/hot_remove" \
+			then	SysCtl "$devnode" "$zclass/hot_remove" \
 					|| status=$?
 			fi
 		fi
@@ -316,7 +316,7 @@ btrfs)
 	mkfs.btrfs -d single -m single \
 		${label:+-L "$label"} ${uuid:+-U "$uuid"} ${1+"$@"} \
 		-- "$devnode" >/dev/null \
-		|| Fatal "mkfs.btrfs $extnode failed"
+		|| Fatal "mkfs.btrfs $devnode failed"
 	$mount || exit 0
 	eval "set -- a $mount_opt"
 	shift
