Support writeback of incompressible/idle pages and writeback_limit

diff --git a/sbin/zram-init b/sbin/zram-init
--- a/sbin/zram-init
+++ b/sbin/zram-init
@@ -5,7 +5,7 @@ Echo() {
 	printf '%s\n' "$*"
 }
 
-if command -v logger
+if command -v logger >/dev/null 2>&1
 then	EchoLog() {
 	Echo "$*"
 	logger "$*"
@@ -52,10 +52,12 @@ IsNumeric() {
 }
 
 Usage() {
-	Echo "Usage: ${0##*/} [options] SIZE [DIR]
+	Echo "Usage: ${0##*/} [options] SIZE|write [DIR]
 Prepare a zram device and use it as swap (resp. mount it under DIR).
 SIZE is the maximal size in megabytes.
 For umounting/freeing the zram device, use SIZE=0.
+When using \"write\" (or anything else starting with \"w\") an idle writeback
+is forced (only makes sense if previously initialized with -w or -W LIMIT).
 If DIR is - then only a filesystem is created in /dev/zram\$DEV (or the device
 is removed if SIZE is 0) but it is not mounted
 (options -o -c -m -T take no effect in this case, of course).
@@ -71,6 +73,9 @@ An empty argument means the same as if the option is not specified.
 -s NUM   Use up to NUM parallel compression streams for the device
 -S MAX   Use maximally MAX megabytes of uncompressed memory for the device
 -b DEV   Use DEV as backing device
+-I       If combined with -b DEV, store incompressible pages to backing device
+-w       If combined with -b DEV, enable idle writeback to backing device
+-W LIMIT As -w but additionally set writeback_limit to LIMIT * 4kB.
 -a ALGO  Set compression algorithm to ALGO (e.g. zstd, lz4, or lzo)
 -c OWNER If specified, chown to OWNER (resp. OWNER:GROUP) after mounting.
          If not specified, the default owner (root:root) is not changed.
@@ -123,13 +128,17 @@ tune2fs_opt=
 zramctl_opt=
 mem_limit=
 backing_dev=
+writeback=false
+writeback_limit=
+incompressible=false
 OPTIND=1
-while getopts 's:S:a:b:c:d:D:m:o:p:t:i:N:L:U:TlkK:M:2:Z:hH' opt
+while getopts 's:S:a:b:Ic:d:D:m:o:p:t:i:N:L:U:wW:TlkK:M:2:Z:hH' opt
 do	case $opt in
 	s)	streams=$OPTARG;;
 	S)	mem_limit=$OPTARG;;
 	a)	algo=$OPTARG;;
 	b)	backing_dev=$OPTARG;;
+	I)	incompressible=:;;
 	c)	owgr=$OPTARG;;
 	d)	dev=$OPTARG;;
 	D)	num=$OPTARG;;
@@ -141,6 +150,9 @@ do	case $opt in
 	N)	inodes=$OPTARG;;
 	L)	label=$OPTARG;;
 	U)	uuid=$OPTARG;;
+	w)	writeback=:;;
+	W)	writeback=:
+		writeback_limit=$OPTARG;;
 	T)	discard=false;;
 	l)	zramctl=false;;
 	k)	keep=:;;
@@ -163,7 +175,22 @@ fi
 : "${dev:=0}" "${prio:=16383}" "${fstype:=ext4}"
 
 IsNumeric "$dev" || Fatal "device $dev is not numeric"
+
+devnode=/dev/zram$dev
+zclass=/sys/class/zram-control
+block=/sys/block/zram$dev
+
+case ${1:-0} in
+w*)
+	SysCtlN idle "$block/writeback" || \
+		Fatal "failed to idle writeback zram$dev"
+	exit;;
+esac
+
 IsNumeric "${1:-0}" || Fatal "size $1 is not numeric"
+IsNumeric "${mem_limit:-0}" || Fatal "mem_limit $mem_limit is not numeric"
+IsNumeric "${writeback_limit:-0}" || \
+	Fatal "writeback_limit $writeback_limit is not numeric"
 
 umount=:
 if [ ${1:-0} -ne 0 ]
@@ -186,9 +213,6 @@ then	swap=false
 		fi
 	fi
 fi
-
-devnode=/dev/zram$dev
-zclass=/sys/class/zram-control
 
 HotAdd() {
 	while :
@@ -229,7 +253,6 @@ then	$umount && exit
 		keep=:
 	}
 fi
-block=/sys/block/zram$dev
 if ! $zramctl || [ -n "$mem_limit" ] || [ -n "${backing_dev:++}" ]
 then	test -d "$block" || Fatal "cannot find $block"
 fi
@@ -257,6 +280,7 @@ fi
 $umount && exit $status
 test -b "$devnode" || HotAdd
 
+
 if $zramctl && [ -z "${backing_dev:++}" ]
 then	eval "set -- a $zramctl_opt"
 	shift
@@ -271,6 +295,22 @@ else	[ -z "$streams" ] || SysCtl "$streams" "$block/max_comp_streams" || \
 	[ -z "${backing_dev:++}" ] || \
 		SysCtlN "$backing_dev" "$block/backing_dev" || \
 		Warning "failed to set zram$dev backing_dev"
+	! $incompressible || SysCtlN huge "$block/write" || \
+		Warning "failed to set zram$dev incompressible writeback"
+	! $writeback || InitWriteback() {
+	SysCtlN all "$block/idle" || {
+		Warning "failed to set zram$dev idle writeback"
+		return
+	}
+	[ -n "${writeback_limit:++}" ] || return 0
+	SysctlN 1 "$block/writeback_limit_enable" || {
+		Warning "failed to enable writeback_limit for zram$dev"
+		return
+	}
+	SysctlN "$writeback_limit" "$block/writeback_limit" || \
+	Warning "failed to set writeback_limit $writeback_limit for zram$dev"
+}
+	! $writeback || InitWriteback
 	SysCtl "$size" "$block/disksize" || Fatal "cannot set zram$dev size"
 fi
 [ -z "$mem_limit" ] || SysCtl "$mem_limit" "$block/mem_limit" || \
